name: 💡 Request a Feature
description: Suggest a new feature or improvement for RS90.
title: "[Feature]: "
labels: [enhancement]
projects: ["cantatacsfr/bug-report-project"]  # Update to match your actual project name or remove if not using Projects
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve RS90! Tell us about the feature you'd like to see.

  - type: input
    id: title
    attributes:
      label: Feature Summary
      description: A short one-line summary of your idea.
      placeholder: Let RS90 auto-detect my TV model
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: What's the use case?
      description: Why do you need this feature? What problem does it solve?
      placeholder: I often use RS90 in hotels, and I need a way to scan unknown TV models...
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: How would it help you or others?
      description: How does it improve the user experience or workflow?
      placeholder: It would save setup time and make RS90 more plug-and-play...
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Any other details?
      description: Include mockups, links, or examples if helpful.
      placeholder: You can also share screenshots or similar apps...
